### ISSUE TITLE
Allow order_by attribute to specify multiple fields

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail-generic-chooser#18]
Hi,

This module is very useful too me, thanks for putting it together. However I do have a model with lots of fields and the ideal sort order needs to take into account several of those fields.

As I see it, the `order_by` attribute is ultimately passed to `django.db.models.query.QuerySet.order_by()` which takes `*field_names` as an argument, but only one argument is passed. I tried a list and a tuple for the `order_by` attribute to no avail.

Is there some Python construct I can use to pass multiple arguments via `order_by`, or is the solution to make `ModelChooserMixin.get_unfiltered_object_list` capable of handing an iterable `order_by` attribute?

Thanks.

**Comment by dkirkham** [comment]
Having had another look at this over the weekend, I think the easiest solution, if/when this module is integrated into wagtail proper, is to allow the `order_by` attribute to be list or tuple like many other similar attributes throughout wagtail and django. Then `ModelChooserMixin.get_unfiltered_object_list()`  makes use of the unpacking operator `*` when passing `order_by` to the QuerySet.
That will break the current code using this module, since a string `order_by` is iterable.
Hope this helps.

**Comment by gasman** [comment]
Fixed in #21.
