### ISSUE TITLE
Change path of javascript generic_chooser files

### ISSUE THREAD

**Issue by Aleksi44** [wagtail/wagtail-generic-chooser#23]
I am trying to change the path of static `generic_chooser` javascript files. I have a django app : `wagtailsvg` available on [this link](https://github.com/Aleksi44/wagtailsvg). To avoid an incorrect overloading of django static loaders, I need to change the path, so I tried :

```
from generic_chooser.widgets import AdminChooser


class AdminSvgChooser(AdminChooser):
    choose_one_text = _("Choose a SVG item")
    choose_another_text = _("Choose another SVG item")
    link_to_chosen_text = _("Edit this SVG item")
    model = Svg
    choose_modal_url_name = 'svg_chooser:choose'
    edit_item_url_name = 'wagtailsvg_svg_modeladmin_edit'

    class Media:
        js = [
	    'wagtailsvg/js/src/chooser-modal.js',
	    'wagtailsvg/js/src/chooser-widget.js',
	]
```

Without success,
static `generic_chooser` javascript files are still fetch.
Do you have any idea how to change the path?
I am doing something wrong?

**Comment by gasman** [comment]
Hi @Aleksi44,
As per https://docs.djangoproject.com/en/3.2/topics/forms/media/#extend , if you don't want `AdminSvgChooser` to inherit `AdminChooser`'s media definitions then you should set `extend = False` on the Media class.
