### ISSUE TITLE
How to change the instances title in the widget chooser

### ISSUE THREAD

**Issue by lmorillas** [wagtail/wagtail-generic-chooser#27]
By default the widget renders the str of the object. Is it possible to configure other field or method in order to show a more usable string of the object?

The ```get_title``` method only works when the object is selected and saved.

```
class ResponsableChooser(AdminChooser):
    model = User
    def get_title(self, instance):
        return str(instance.get_full_name())
```

In my example I need a chooser for app users. Using the **User** model by default the chooser renders the username in the suer list, not the ```instance.get_full_name()``` value for example.

**Comment by lmorillas** [comment]
Solved with a proxy class.

**Comment by bmihelac** [comment]
What is displayed is defined in [get_object_string](https://github.com/wagtail/wagtail-generic-chooser/blob/b49d1354c0be4cf946cd7264861320aec42b2925/generic_chooser/views.py#L56-L60)  method of `chooser_mixin_class`:



```python
from generic_chooser.views import ModelChooserViewSet, ModelChooserMixin
from wagtail.core.models import Collection


class CustomModelChooserMixin(ModelChooserMixin):
    def get_object_string(self, instance):
        return get_tree_title(instance, 1)


class CollectionChooserViewSet(ModelChooserViewSet):
    chooser_mixin_class = CustomModelChooserMixin
    model = Collection
```
