### ISSUE TITLE
Expected UI issues with Wagtail 3.0 release

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail-generic-chooser#50]
The [Wagtail 3.0 first release candidate](https://github.com/wagtail/wagtail/discussions/8362) is out. There are large UI changes in this release, for which we have [reviewed expected breakage in third-party UI customisations](https://github.com/wagtail/wagtail/discussions/7739#discussioncomment-2615089).

This is beyond what we do with our normal breaking changes policy, since the majority of those changes are on parts of Wagtail that haven’t been publicly supported / documented in any way. To make sure this goes smoothly anyway, I’m here to provide an advance notice of what we’re aware of with this specific package 🙂 

In the case of wagtail-generic-chooser, the main issue is reliance on Wagtail’s internal tabs implementation:

```text
wagtail/wagtail/wagtail-generic-chooser/generic_chooser/templates/generic_chooser/tabbed_modal.html
10:    <ul class="tab-nav merged" data-tab-nav>
```

Here is our [guidance on replacing Bootstrap tabs](https://github.com/wagtail/wagtail/discussions/7739#user-content-2022-04-22-breaking-changes-in-ui-code-bootstrap-tabs), and our [proposal for a tabs component API](https://github.com/wagtail/wagtail/issues/8408).

**Comment by gasman** [comment]
Completed in #53.
