### ISSUE TITLE
Override save method on create

### ISSUE THREAD

**Issue by joahim** [wagtail/wagtail-generic-chooser#57]
Is there an easy way to override the save method when creating objects within the chooser? Similar to Django admin's [save_model](https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.save_model) mechanism.

In my case, I would need to set the current user (from request) on the object being created.

**Comment by gasman** [comment]
This can be done by overriding the `form_valid` method:

https://github.com/wagtail/wagtail-generic-chooser/blob/7d26029dd10d0a1e1f67fb39f0a9a768df47bce0/generic_chooser/views.py#L457-L462
