### ISSUE TITLE
Searching in ModelChooserMixin could use autocomplete instead of search

### ISSUE THREAD

**Issue by bmihelac** [wagtail/wagtail-generic-chooser#80]
Hi all,

Apologies if this has been discussed before or if it is not meaningful because this library supports multiple Wagtail versions.

Searching in `ModelChooserMixin` is currently done using the `search_backend.search(search_term, object_list)`. [link](https://github.com/wagtail/wagtail-generic-chooser/blob/main/generic_chooser/views.py#L262-L269). It might be useful to default to `autocomplete`, if available, similar to how Wagtail does for its built-in choosers, such as *Images*.

For reference, here is the Wagtail code:
[https://github.com/wagtail/wagtail/blob/a80c7ca60eccf9df60f90d3f10da2d506776c13d/wagtail/admin/forms/choosers.py#L81-L94](https://github.com/wagtail/wagtail/blob/a80c7ca60eccf9df60f90d3f10da2d506776c13d/wagtail/admin/forms/choosers.py#L81-L94)

**Comment by gasman** [comment]
Thanks for the report @bmihelac! Now that [Wagtail's own ChooserViewSet](https://docs.wagtail.org/en/stable/extending/generic_views.html#chooserviewset) is feature-complete with wagtail-generic-chooser's feature set, it's unlikely that we'll be developing it further to take advantage of other Wagtail enhancements (such as the work to make autocompletion search consistent across all backends in 5.1). I'll update the readme to clarify this.

**Comment by bmihelac** [comment]
Thanks for the info @gasman, I did not know that.
